spring:
  application:
    name: url_shortener
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  liquibase:
    enabled: true
  jta:
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate: 'null'
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  mvc:
    log-request-details: true
#logging:
#  structured:
#    format:
#      console: ecs

redis:
  ttl: 120
server:
  address: 0.0.0.0
  port: 9090